DROP TABLE IF EXISTS order_product;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS member;

create table member (
                        id bigint generated by default as identity,
                        email varchar(255),
                        password varchar(255),
                        password_fail_cnt integer,
                        status integer,
                        type varchar(255),
                        created_time timestamp,
                        updated_time timestamp,
                        deleted_time timestamp,
                        primary key (id)
);

create table orders (
                       id bigint generated by default as identity,
                       order_status varchar(255),
                       payment varchar(255),
                       total_price integer,
                       member_id bigint,
                       created_time timestamp,
                       updated_time timestamp,
                       cancel_time timestamp,
                       primary key (id)
);

create table product (
                         id bigint generated by default as identity,
                         category varchar(255),
                         description varchar(255),
                         name varchar(255),
                         price integer,
                         stock integer,
                         created_time timestamp,
                         updated_time timestamp,
                         deleted_time timestamp,
                         primary key (id)
);

create table order_product (
                               id bigint generated by default as identity,
                               count integer,
                               product_price integer,
                               status integer,
                               total_price integer,
                               order_id bigint,
                               product_id bigint,
                               created_time timestamp,
                               updated_time timestamp,
                               cancel_time timestamp,
                               primary key (id)
);